import streamlit as st
import pandas as pd
from prophet import Prophet
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime
from fpdf import FPDF
import io
import requests
import google.generativeai as genai
from streamlit_lottie import st_lottie
from supabase import create_client, Client

# --- 0. BRANDING & SECURITY CONFIG ---
PRODUCT_NAME = "Pulse AI"
BRAND_NAME = "Hope Tech"

st.set_page_config(page_title=f"{PRODUCT_NAME}: Enterprise Forecasting", layout="wide")

# Custom UI Styling for a Professional Dark Theme
st.markdown("""
    <style>
    .stApp { background-color: #0e1117; color: #ffffff; }
    .stSidebar { background-color: #161b22; border-right: 1px solid #30363d; }
    .glass-card {
        background: rgba(255, 255, 255, 0.05); border-radius: 12px;
        padding: 20px; border: 1px solid rgba(255, 255, 255, 0.1); margin-bottom: 20px;
    }
    .main-title { font-size: 38px; font-weight: bold; color: #00B0F6; }
    </style>
    """, unsafe_allow_html=True)

def init_connections():
    """Initialize Database and AI Model connections from secrets."""
    sb, ai = None, None
    try:
        if "SUPABASE_URL" in st.secrets and "SUPABASE_KEY" in st.secrets:
            url = st.secrets["SUPABASE_URL"]
            key = st.secrets["SUPABASE_KEY"]
            sb = create_client(url, key)
        if "GOOGLE_API_KEY" in st.secrets:
            genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])
            ai = genai.GenerativeModel('gemini-1.5-flash')
    except Exception as e:
        st.error(f"Connection Error: {e}")
    return sb, ai

supabase, ai_model = init_connections()

def log_visitor_analytics():
    """Logs visitor country to Supabase for the Admin Dashboard."""
    if supabase:
        try:
            # Simple IP-based geo-location
            geo_data = requests.get('https://ipapi.co/json/').json()
            country = geo_data.get('country_name', 'Unknown')
            supabase.table("site_analytics").insert({
                "country": country, 
                "created_at": datetime.now().isoformat()
            }).execute()
        except: pass

def save_forecast_to_db(project_name, forecast_df):
    """Saves analyzed project data to history table."""
    if supabase:
        try:
            data_json = forecast_df.to_json(orient='records')
            data = {
                "project_name": project_name, 
                "forecast_data": data_json,
                "created_at": datetime.now().isoformat()
            }
            supabase.table("forecast_history").insert(data).execute()
        except Exception as e:
            st.sidebar.error(f"DB Write Failed: {e}")

# --- 1. ANALYTICS ENGINE (PROPHET) ---
@st.cache_resource
def run_forecast_model(df, periods, freq):
    """Core forecasting engine using Additive Prophet Model."""
    model = Prophet(yearly_seasonality=True, weekly_seasonality=True, daily_seasonality=False)
    model.fit(df)
    future = model.make_future_dataframe(periods=periods, freq=freq)
    forecast = model.predict(future)
    return forecast, model

# --- 2. PDF REPORT GENERATOR ---
def create_pdf_report(hist_total, avg_val, proj_total, status, growth_pct, freq_label, curr_sym, curr_name):
    """Generates a professional PDF summary of the findings."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=f"{PRODUCT_NAME} Executive Summary", ln=True, align='C')
    pdf.ln(10)
    
    display_curr = curr_sym if curr_sym not in ["GH₵", "₦", "د.إ", "﷼"] else curr_name.split(" ")[0]
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Key Performance Indicators:", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(200, 8, txt=f"- Lifetime Historical Amount: {display_curr}{hist_total:,.2f}", ln=True)
    pdf.cell(200, 8, txt=f"- Average Amount per {freq_label}: {display_curr}{avg_val:,.2f}", ln=True)
    pdf.cell(200, 8, txt=f"- Total Projected Amount (Horizon): {display_curr}{proj_total:,.2f}", ln=True)
    pdf.ln(5)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Strategic AI Insights:", ln=True)
    pdf.set_font("Arial", '', 11)
    insight_text = (f"The model identifies a market {status} of approximately {abs(growth_pct):.1f}% "
                    f"over the forecasted horizon. Generated by {BRAND_NAME} Analytics.")
    pdf.multi_cell(0, 8, txt=insight_text)
    
    return pdf.output(dest='S').encode('latin-1', 'replace')

# --- 3. UI INITIALIZATION & SIDEBAR ---
currency_lookup = {
    "USD ($)": "$", "NGN (₦)": "₦", "EUR (€)": "€", "GBP (£)": "£",
    "GHS (GH₵)": "GH₵", "ZAR (R)": "R", "KES (KSh)": "KSh", "CAD ($)": "$",
    "AUD ($)": "$", "JPY (¥)": "¥", "INR (₹)": "₹", "CNY (¥)": "¥",
    "AED (د.إ)": "DH ", "SAR (﷼)": "SR "
}

with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/1684/1684374.png", width=80)
    st.title(BRAND_NAME)
    
    menu = st.tabs(["🚀 Control", "👨‍💻 Engineer", "💖 Support", "🔐 Admin"])
    
    with menu[0]:
        st.header("Administration")
        project_name = st.text_input("Project Name:", value="Alpha_Project")
        selected_curr_name = st.selectbox("Reporting Currency:", options=list(currency_lookup.keys()), index=0)
        curr_sym = currency_lookup[selected_curr_name]
        input_method = st.radio("Data Source:", ["CSV Upload", "Manual Entry"])
        st.divider()
        st.header("Analysis Tuning")
        ma_window = st.slider("Smoothing Window (Days):", min_value=2, max_value=90, value=7)
        if st.button("🔄 Reset System"):
            st.session_state.clear()
            st.rerun()

    with menu[1]:
        st.subheader("Monivi Hope")
        st.caption("Data & Analytics Engineer")
        st.write("Specializing in Enterprise Business Intelligence.")
        st.markdown("[📩 Contact Support](mailto:moniviogi41@gmail.com)")
        st.markdown("[🔗 Linktree](https://linktr.ee/MoniviHope)")

    with menu[2]:
        st.subheader("Show Love")
        st.write("Support the development of Pulse AI.")
        st.link_button("💝 Tip via Selar", "https://selar.com/showlove/hopetech", type="primary")

    with menu[3]:
        admin_pass = st.text_input("Admin Key", type="password")
        is_admin = (admin_pass == "Ibiene2003#")

# --- 4. ADMIN DASHBOARD LOGIC ---
if is_admin:
    st.title("🔐 Enterprise Admin Intelligence")
    if supabase:
        try:
            res = supabase.table("site_analytics").select("*").execute()
            df_admin = pd.DataFrame(res.data)
            if not df_admin.empty:
                col1, col2 = st.columns(2)
                with col1:
                    fig_admin = px.pie(df_admin, names='country', title="Global User Distribution", hole=0.3)
                    st.plotly_chart(fig_admin, use_container_width=True)
                with col2:
                    df_admin['created_at'] = pd.to_datetime(df_admin['created_at'])
                    traffic = df_admin.set_index('created_at').resample('D').count()
                    st.line_chart(traffic['country'])
        except: st.error("Could not load analytics.")
    st.stop() # Prevents admin from seeing the normal user app simultaneously

# --- 5. DATA INGESTION ---
log_visitor_analytics()
st.markdown(f'<p class="main-title">📈 {PRODUCT_NAME} Strategic Forecasting</p>', unsafe_allow_html=True)

col_main, col_ai = st.columns([2.5, 1])

with col_main:
    df_input = None
    if input_method == "CSV Upload":
        file = st.file_uploader("Upload Business Data (CSV)", type="csv")
        if file:
            df_input = pd.read_csv(file)
            st.subheader("📋 Step 1: Data Schema")
            st.dataframe(df_input.head(3), use_container_width=True)
            c1, c2 = st.columns(2)
            with c1: user_date_col = st.selectbox("Timeline Column:", df_input.columns, key="date_sel")
            with c2: user_val_col = st.selectbox("Value Column:", df_input.columns, key="val_sel")
    else:
        st.subheader("📋 Step 1: Manual Entry")
        manual_data = st.text_area("Input Values (comma separated):", placeholder="1400, 2000, 420...")
        if manual_data:
            try:
                vals = [float(x.strip()) for x in manual_data.split(",")]
                df_input = pd.DataFrame({"y": vals})
                st.success(f"Captured {len(vals)} data points.")
            except: st.error("Numbers and commas only.")

    # Configuration and Execution
    if df_input is not None:
        st.subheader("⚙️ Step 2: Analysis Configuration")
        col_a, col_b = st.columns(2)
        with col_a:
            freq_label = st.selectbox("Interval:", ["Yearly", "Monthly", "Weekly", "Daily"], index=1)
            freq_map = {"Yearly": "YS", "Monthly": "MS", "Weekly": "W", "Daily": "D"}
        with col_b:
            horizon = st.number_input(f"Horizon ({freq_label}):", min_value=1, value=24)

        if st.button("🚀 Execute Analysis", type="primary"):
            try:
                if input_method == "CSV Upload":
                    working_df = df_input[[user_date_col, user_val_col]].copy().rename(columns={user_date_col: 'ds', user_val_col: 'y'})
                    working_df['ds'] = pd.to_datetime(working_df['ds'], errors='coerce')
                else:
                    working_df = df_input.copy()
                    fixed_today = pd.Timestamp.today().normalize()
                    working_df['ds'] = pd.date_range(end=fixed_today, periods=len(working_df), freq=freq_map[freq_label])
                
                working_df = working_df.dropna(subset=['ds', 'y']).sort_values('ds') 
                working_df = working_df.groupby('ds')['y'].sum().reset_index()
                working_df['ma'] = working_df['y'].rolling(window=ma_window, min_periods=1).mean()

                with st.spinner(f"{PRODUCT_NAME} is processing AI data..."):
                    f_data, f_model = run_forecast_model(working_df, horizon, freq_map[freq_label])
                    st.session_state.update({'forecast': f_data, 'model': f_model, 'history': working_df, 'analyzed': True})
                    save_forecast_to_db(project_name, working_df)
                    st.success("Analysis Complete!")
            except Exception as e: st.error(f"Analysis Error: {e}")

# --- 6. AI ANALYST (SIDEBAR CARD) ---
with col_ai:
    st.markdown('<div class="glass-card">', unsafe_allow_html=True)
    st.subheader("🤖 Pulse AI Analyst")
    if st.session_state.get('analyzed') and ai_model:
        user_query = st.text_input("Ask about the forecast insights:")
        if user_query:
            hist_sum = st.session_state['history']['y'].sum()
            prompt = f"Data: {PRODUCT_NAME} analyzed a total revenue of {hist_sum}. Question: {user_query}. Respond as a helpful business peer."
            with st.spinner("AI Thinking..."):
                response = ai_model.generate_content(prompt)
                st.info(response.text)
    else:
        st.write("Please run an analysis to enable the AI Chat Analyst.")
    st.markdown('</div>', unsafe_allow_html=True)

# --- 7. VISUALIZATION DASHBOARD ---
if st.session_state.get('analyzed'):
    st.divider()
    hist, fcst, model = st.session_state['history'], st.session_state['forecast'], st.session_state['model']
    future_only = fcst.tail(horizon)
    projected_sum = future_only['yhat'].sum()
    
    start_val = future_only['yhat'].iloc[0]
    end_val = future_only['yhat'].iloc[-1]
    growth_pct = ((end_val - start_val) / start_val) * 100 if start_val != 0 else 0
    status = "increase" if growth_pct > 0 else "decrease"

    # Core Metric Cards
    m1, m2, m3 = st.columns(3)
    m1.metric("Lifetime Amount", f"{curr_sym}{hist['y'].sum():,.2f}")
    m2.metric(f"Avg per {freq_label}", f"{curr_sym}{hist['y'].mean():,.2f}")
    m3.metric("Projected Total", f"{curr_sym}{projected_sum:,.2f}")

    st.write("### 📊 Business Intelligence Perspectives")
    view = st.radio("Switch View:", ["AI Strategic Forecast", "Anomaly Detector", "Model Performance", "Monthly History", "Weekly Patterns", "Annual Growth"], horizontal=True)
    fig = go.Figure()

    if view == "AI Strategic Forecast":
        fig.add_trace(go.Scatter(x=future_only['ds'], y=future_only['yhat_upper'], mode='lines', line=dict(width=0), showlegend=False))
        fig.add_trace(go.Scatter(x=future_only['ds'], y=future_only['yhat_lower'], mode='lines', line=dict(width=0), fill='toself', fillcolor='rgba(0,176,246,0.1)', name="Probability Range"))
        show_labels = "lines+markers+text" if horizon <= 24 else "lines+markers"
        fig.add_trace(go.Scatter(x=future_only['ds'], y=future_only['yhat'], mode=show_labels, line=dict(color='#00B0F6', width=4), text=[f"{curr_sym}{x:,.0f}" for x in future_only['yhat']], textposition="top center", name="AI Prediction"))

    elif view == "Anomaly Detector":
        perf = fcst.set_index('ds')[['yhat', 'yhat_lower', 'yhat_upper']].join(hist.set_index('ds'))
        anoms = perf[(perf['y'] > perf['yhat_upper']) | (perf['y'] < perf['yhat_lower'])]
        c1, c2, c3 = st.columns(3)
        c1.metric("Anomalies Found", len(anoms))
        c2.metric("Highest Spike", f"{curr_sym}{anoms['y'].max():,.0f}" if not anoms.empty else "0")
        c3.metric("Deepest Dip", f"{curr_sym}{anoms['y'].min():,.0f}" if not anoms.empty else "0")
        fig.add_trace(go.Scatter(x=perf.index, y=perf['y'], mode='lines', name='Actual Performance', line=dict(color='#FFFFFF', width=1)))
        fig.add_trace(go.Scatter(x=anoms.index, y=anoms['y'], mode='markers', name='Anomaly', marker=dict(color='#FF4B4B', size=10)))
        st.dataframe(anoms[['y']].rename(columns={'y': 'Irregular Amount'}).style.format(lambda x: f"{curr_sym}{x:,.2f}"), use_container_width=True)

    elif view == "Model Performance":
        st.info(f"💡 Comparing Raw Data vs. {ma_window}-Day Smoothing vs. AI Fit.")
        fig.add_trace(go.Scatter(x=hist['ds'], y=hist['y'], mode='lines', name='Raw Data', line=dict(color='rgba(255,255,255,0.1)', width=1)))
        fig.add_trace(go.Scatter(x=hist['ds'], y=hist['ma'], mode='lines', name='Moving Average', line=dict(color='#00FFCC', width=3)))
        fig.add_trace(go.Scatter(x=fcst['ds'][:len(hist)], y=fcst['yhat'][:len(hist)], mode='lines', line=dict(dash='dash', color='orange'), name='AI Fit'))

    elif view == "Monthly History":
        monthly = hist.set_index('ds').resample('MS')['y'].sum().reset_index()
        fig.add_trace(go.Bar(x=monthly['ds'], y=monthly['y'], marker_color="#636EFA", text=[f"{curr_sym}{x:,.0f}" for x in monthly['y']], textposition="outside", name="Monthly Total"))

    elif view == "Weekly Patterns":
        days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        sample_week = pd.DataFrame({'ds': pd.date_range('2024-01-01', periods=7)}) 
        weekly_comp = model.predict(sample_week)[['ds', 'weekly']]
        fig.add_trace(go.Bar(x=days, y=weekly_comp['weekly'], marker_color='#00FFCC'))

    elif view == "Annual Growth":
        yearly = hist.set_index('ds').resample('YS')['y'].sum().reset_index()
        fig.add_trace(go.Scatter(x=yearly['ds'], y=yearly['y'], mode='lines+markers+text', line=dict(color="#EF553B", width=4), text=[f"{curr_sym}{x:,.0f}" for x in yearly['y']], textposition="top center", name="Annual Performance"))

    fig.update_layout(template="plotly_dark", height=600, hovermode="x unified")
    st.plotly_chart(fig, use_container_width=True)

    # Export Section
    st.subheader("📥 Export Reports")
    ex1, ex2 = st.columns(2)
    with ex1:
        csv = fcst.to_csv(index=False).encode('utf-8')
        st.download_button(label="Download CSV Data", data=csv, file_name=f'{project_name}_forecast.csv', mime='text/csv')
    with ex2:
        pdf_bytes = create_pdf_report(hist['y'].sum(), hist['y'].mean(), projected_sum, status, growth_pct, freq_label, curr_sym, selected_curr_name)
        st.download_button(label="Download PDF Summary", data=pdf_bytes, file_name=f'{project_name}_summary.pdf', mime='application/pdf')

    st.divider()
    st.subheader("💡 Strategic Insights for Management")
    with st.expander("Interpret Results", expanded=True):
        st.write(f"""
        * **Logic:** Built on an Additive Prophet Architecture.
        * **Trajectory:** Identifies an AI-driven **{status}** toward **{curr_sym}{end_val:,.2f}**.
        * **Summary:** Total expected volume for the next {horizon} {freq_label.lower()} is **{curr_sym}{projected_sum:,.2f}**.
        """)

else:
    st.info("💡 Please upload data and click 'Execute Analysis' to generate reports.")

# --- 8. FOOTER ---
st.markdown("---")
st.markdown(f"<center>{BRAND_NAME} | Simple, Smart & Productive</center>", unsafe_allow_html=True)
